instructions:
	g++ --std=c++11 -I ../include/ -o instructions instructions.cpp ../src/ProbeBound.cpp ../src/VersionState.cpp ../src/NBHashTable.cpp

default:
	g++ --std=c++11 -I ../include/ -o atomict atomictypes.cpp ../src/ProbeBound.cpp ../src/VersionState.cpp
